### ISSUE TITLE
side scroll issue

### ISSUE THREAD

**Issue by rimmesbe** [missreyes/prj-rev-bwfs-tea-cozy#1]
Your site has a slight side scroller issue. That is because the copyright sections has width 100% and margin left. This will push the width of the section greater that 100% aka greater than the parent (body).

https://github.com/missreyes/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L236-L238

**Comment by missreyes** [comment]
Changed it to "max-width: 1200px", still need to test.

**Comment by missreyes** [comment]
Removed width altogether & used "align-self: flex-start" then tested. Issue fixed! Not sure if I'm supposed to close these also?
