### ISSUE TITLE
p tag with img

### ISSUE THREAD

**Issue by rimmesbe** [missreyes/prj-rev-bwfs-tea-cozy#2]
A paragraph tag is not the correct choice to put the logo image inside of. Paragraph tags come with margins top/bottom and block display. They are designed for blocks of text. I would use a span or maybe not even wrap it in another element in this case. 

https://github.com/missreyes/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html#L13

**Comment by missreyes** [comment]
Changed to "Span" but still need to test.

**Comment by missreyes** [comment]
Changed to "Span" but tested and fixed.
