### ISSUE TITLE
camel case vs convention

### ISSUE THREAD

**Issue by rimmesbe** [missreyes/prj-rev-bwfs-tea-cozy#3]
In css the common convention for naming is to split words with '-' or sometimes '_' 
.big-box
.small-section
camelCase is used in other coding languages like javascript.

https://github.com/missreyes/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html#L21-L23

**Comment by missreyes** [comment]
Changed everything to have a "-".

**Comment by missreyes** [comment]
Tested and it didn't cause any issues.
