### ISSUE TITLE
footer is a div

### ISSUE THREAD

**Issue by rimmesbe** [missreyes/prj-rev-bwfs-tea-cozy#5]
A footer tag is just a div with a fancy name. Same with header, nav, main, article, section etc.
No need for and extra div around it. In general I'm seeing a lot  of divs with no classes or id's which is a red flag. Generally a div with no attribute means either it's an unnecessary div or the selector being used is not optimal.
Better to target a class than a chain:
.div-class { }  is better than .parent-class div { }

**Comment by missreyes** [comment]
I tried it without on the footer but I couldn't get it to work correctly.

**Comment by missreyes** [comment]
Removed `<div>`'s & added "align-items: center;" to CSS and it worked.
