### ISSUE TITLE
inline-flex

### ISSUE THREAD

**Issue by rimmesbe** [missreyes/prj-rev-bwfs-tea-cozy#6]
I'm seeing inline-flex used a lot which is not per usual. Inline flex makes that element inline display and also flex display. Not used very often. In the cases I see you using it either flex will due, or inline will do. Not both.

https://github.com/missreyes/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L227

**Comment by missreyes** [comment]
Does this mean that I should change all of them to flex?

**Comment by rimmesbe** [comment]
you can. The only place that it's probably ok to use inline is the nav bar

**Comment by missreyes** [comment]
There were a couple of more places that needed it, but that might change if I change up the black boxes & the titles under the images, we're still talking about.
